[project]
name = "rc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["flask>=3.1.2", "uvicorn>=0.30.0", "watchdog>=4.0.0"]
